WIP min/max configuration
hashicorp/consul-api-gateway pull request #198
Opened 2022-05-24 16:07 UTC by sarahalsmiller

### Changes proposed in this PR:
- add minInstances and maxInstances as configurable fields on gatewayclassconfig

### How I've tested this PR:
- running unit tests
- creating a local kind cluster

### How I expect reviewers to test this PR:
-passing unit tests

### Checklist:
- [ ] Tests added
- [ ] CHANGELOG entry added 
  > Run `make changelog-entry` for guidance in authoring a changelog entry, and
  > commit the resulting file, which should have a name matching your PR number.
  > Entries should use imperative present tense (e.g. Add support for...)

2022-05-26 17:50 UTC, claire-labry approved these changes
I just reviewed the CRT bits (.release/ci.hcl and .github/workflows/build.yml) and it all checks out to me!

2022-05-27 20:00 UTC, nathancoleman requested changes
Awesome job! This works swimmingly, so most of my comments are just about test things

2022-05-27 20:03 UTC, sarahalsmiller commented on internal/k8s/reconciler/gateway.go
> -	//get current deployment so user set replica count isn't overridden by defaul values
I don't think I meant to delete it, lol

2022-05-27 21:27 UTC, nathancoleman approved these changes

2022-05-27 21:28 UTC, merged