Implement BackendNotFound reason for ResolvedRefs condition on xRoute
hashicorp/consul-api-gateway pull request #291
Opened 2022-07-15 20:01 UTC by nathancoleman

### Changes proposed in this PR:

### How I've tested this PR:

### How I expect reviewers to test this PR:

### Checklist:
- [ ] Tests added
- [ ] CHANGELOG entry added 
  > Run `make changelog-entry` for guidance in authoring a changelog entry, and
  > commit the resulting file, which should have a name matching your PR number.
  > Entries should use imperative present tense (e.g. Add support for...)

2022-07-19 16:54 UTC, mikemorris requested changes
~~LGTM to merge _before_ #290, as it's not impacted by the potential upstream logic conflict described in https://github.com/hashicorp/consul-api-gateway/pull/290#pullrequestreview-1043784170~~

I _think_ the usage of `NewConsulResolutionError` at https://github.com/hashicorp/consul-api-gateway/blob/f19a977cc0f66d9a88e0ec48860440e3b6c92e3c/internal/k8s/service/resolver.go#L257 could be updated to instead return `NewBackendNotFoundError` too.

I was curious if there are any remaining valid uses of `NewConsulResolutionError`, or could if it be removed now, but I'm not sure if https://github.com/hashicorp/consul-api-gateway/blob/f19a977cc0f66d9a88e0ec48860440e3b6c92e3c/internal/k8s/service/resolver.go#L280-L283 sufficiently maps to `NewBackendNotFoundError` to remove it entirely? Maybe?

~~Holding at least until #290 merges and this gets rebased for CI tests actually run.~~

Looks like there's a failing e2e test.

2022-07-19 16:57 UTC, mikemorris commented on internal/k8s/service/resolver.go
> +		return nil, NewBackendNotFoundError(fmt.Sprintf("consul service (%s, %s) not found", consulNamespace, consulName))
Are these other uses of `NewConsulResolutionError`, or could it be removed now?

2022-07-20 14:23 UTC, andrewstucki commented
@mikemorris yeah, I think that the line you commented here:

> I was curious if there are any remaining valid uses of NewConsulResolutionError, or could if it be removed now, but I'm not sure if ... sufficiently maps to NewBackendNotFoundError to remove it entirely? Maybe?

is different enough from not being able to find a backend -- i.e. it found one, but problematically it found more than one -- that it probably should be kept its own error type.

2022-07-20 16:35 UTC, mikemorris approved these changes

2022-07-20 16:49 UTC, merged