Add basic controller CLI entrypoint
hashicorp/consul-api-gateway pull request #352
Opened 2022-09-09 01:15 UTC by andrewstucki

### Changes proposed in this PR:

This adds an entrypoint for the API server. As we flesh out the API implementation it'll need some tweaking, but for now it spins up a server based off of the configuration flags passed to it and a goroutine that registers the controller as a Consul service along with periodically updating the TTL health check it registers.

It also scaffolds out an entrypoint for returning controller "health" that we'll want to build an internal endpoint for that grabs all of the instance health from the controllers that have been registered in Consul.

### How I've tested this PR:

Manually, here are some outputs/screenshots:

In one terminal:

```
➜  consul-api-gateway git:(vm-controller-cli-entrypoint) ./consul-api-gateway controller
```

In another:

```
➜  consul-api-gateway git:(vm-controller-cli-entrypoint) ./consul-api-gateway gateways list
There was an error sending the request:
	server error - code: 501, message: Not implemented
➜  consul-api-gateway git:(vm-controller-cli-entrypoint) ./consul-api-gateway gateways delete foo
Successfully deleted Gateway: foo
```

In the first terminal again after a Ctrl+C:

```
➜  consul-api-gateway git:(vm-controller-cli-entrypoint) ./consul-api-gateway controller
2022-09-08T21:11:49.824-0400 [INFO]  v1/gateways.go:49: controller: deleting gateway: namespace=default name=foo
^CStopping Gateway API controller
```

Screenshot of the  registered Consul service:

<img width="882" alt="Screen Shot 2022-09-08 at 9 12 55 PM" src="https://user-images.githubusercontent.com/3577250/189251712-d2e8d92f-09d8-4adc-93a1-a7d4deeca6e3.png">

### Checklist:
- [ ] Tests added
- [ ] CHANGELOG entry added 
  > Run `make changelog-entry` for guidance in authoring a changelog entry, and
  > commit the resulting file, which should have a name matching your PR number.
  > Entries should use imperative present tense (e.g. Add support for...)

2022-09-13 15:03 UTC, nathancoleman requested changes
Nice work! I appreciate the examples + screenshots in the PR body and the code readability 🤩

2022-09-13 15:14 UTC, andrewstucki commented on internal/commands/controller/command.go
> +	c.Flags.StringVar(&c.flagConsulToken, "consul-token", "", "Token to use for Consul client.")
Yeah, so the environment variable and config file binding will eventually come, but this is just to get a handle on exactly what we need to configure for the controller to run and talk to all the needed components.

2022-09-13 15:21 UTC, nathancoleman commented on internal/api/server.go
> +		}
I wasn't thinking about logging errors. Was thinking more of `"Cert and key provided, serving TLS"` and then the inverse case

2022-09-13 15:22 UTC, andrewstucki commented on internal/api/server.go
> +		}
Ah, I see, so you're saying, log `Serving over http` v. `Serving over https` like messages. 👍

2022-09-13 15:48 UTC, merged

2022-09-19 15:40 UTC, mikemorris commented on internal/consul/registration.go
>  func (s *ServiceRegistry) Register(ctx context.Context) error {
Is this currently being used only for registering the API Gateway controller service?